"""empty message

Revision ID: 2d8300856f5d
Revises: 8681e233a078
Create Date: 2025-12-16 19:02:48.860363

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d8300856f5d"
down_revision: Union[str, Sequence[str], None] = "8681e233a078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("urls", sa.Column("last_pars", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("urls", "last_pars")
    # ### end Alembic commands ###
