"""empty message

Revision ID: 8681e233a078
Revises:
Create Date: 2025-12-13 22:33:54.703961

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8681e233a078"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("url_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("scheme", sa.String(length=16), nullable=False),
        sa.Column("domain", sa.String(length=256), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("param", sa.Text(), nullable=True),
        sa.Column("anchor", sa.Text(), nullable=True),
        sa.CheckConstraint("port >= 0 AND port <= 65535"),
        sa.PrimaryKeyConstraint("url_id"),
    )
    op.create_table(
        "links",
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("source_url_id", sa.BigInteger(), nullable=False),
        sa.Column("target_url_id", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(length=16), nullable=False),
        sa.Column("attr", sa.String(length=16), nullable=True),
        sa.Column("field", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_url_id"],
            ["urls.url_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_url_id"],
            ["urls.url_id"],
        ),
        sa.PrimaryKeyConstraint("link_id"),
    )
    op.create_table(
        "responses",
        sa.Column("response_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("url_id", sa.BigInteger(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("h1", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("canonical", sa.Text(), nullable=True),
        sa.Column("redirect", sa.Text(), nullable=True),
        sa.CheckConstraint("status_code >= 100 AND status_code < 600"),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["urls.url_id"],
        ),
        sa.PrimaryKeyConstraint("response_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("responses")
    op.drop_table("links")
    op.drop_table("urls")
    # ### end Alembic commands ###
