"""empty message

Revision ID: ddf6d44b9ce3
Revises: 2d8300856f5d
Create Date: 2025-12-17 17:41:40.480032

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddf6d44b9ce3"
down_revision: Union[str, Sequence[str], None] = "2d8300856f5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("follow", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "follow")
    # ### end Alembic commands ###
